/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        delete?: never;
        get: operations["AppController_getHello"];
        head?: never;
        options?: never;
        parameters: {
            cookie?: never;
            header?: never;
            path?: never;
            query?: never;
        };
        patch?: never;
        post?: never;
        put?: never;
        trace?: never;
    };
    "/api/bets/createBet": {
        delete?: never;
        get?: never;
        head?: never;
        options?: never;
        parameters: {
            cookie?: never;
            header?: never;
            path?: never;
            query?: never;
        };
        patch?: never;
        post: operations["BetsController_createBet"];
        put?: never;
        trace?: never;
    };
    "/api/bets/newest": {
        delete?: never;
        get: operations["BetsController_getNewestBets"];
        head?: never;
        options?: never;
        parameters: {
            cookie?: never;
            header?: never;
            path?: never;
            query?: never;
        };
        patch?: never;
        post?: never;
        put?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    headers: never;
    parameters: never;
    pathItems: never;
    requestBodies: never;
    responses: never;
    schemas: {
        CreateBetDto: Record<string, never>;
    };
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            cookie?: never;
            header?: never;
            path?: never;
            query?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                content?: never;
                headers: {
                    [name: string]: unknown;
                };
            };
        };
    };
    BetsController_createBet: {
        parameters: {
            cookie?: never;
            header?: never;
            path?: never;
            query?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBetDto"];
            };
        };
        responses: {
            201: {
                content?: never;
                headers: {
                    [name: string]: unknown;
                };
            };
        };
    };
    BetsController_getNewestBets: {
        parameters: {
            cookie?: never;
            header?: never;
            path?: never;
            query?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                content?: never;
                headers: {
                    [name: string]: unknown;
                };
            };
        };
    };
}
