/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateBetRouteImport } from './routes/createBet'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BetsBetUrlRouteImport } from './routes/bets.$betUrl'

const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateBetRoute = CreateBetRouteImport.update({
  id: '/createBet',
  path: '/createBet',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BetsBetUrlRoute = BetsBetUrlRouteImport.update({
  id: '/bets/$betUrl',
  path: '/bets/$betUrl',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/createBet': typeof CreateBetRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/bets/$betUrl': typeof BetsBetUrlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/createBet': typeof CreateBetRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/bets/$betUrl': typeof BetsBetUrlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/createBet': typeof CreateBetRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/bets/$betUrl': typeof BetsBetUrlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/badges'
    | '/createBet'
    | '/login'
    | '/overview'
    | '/bets/$betUrl'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/badges' | '/createBet' | '/login' | '/overview' | '/bets/$betUrl'
  id:
    | '__root__'
    | '/'
    | '/badges'
    | '/createBet'
    | '/login'
    | '/overview'
    | '/bets/$betUrl'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BadgesRoute: typeof BadgesRoute
  CreateBetRoute: typeof CreateBetRoute
  LoginRoute: typeof LoginRoute
  OverviewRoute: typeof OverviewRoute
  BetsBetUrlRoute: typeof BetsBetUrlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/createBet': {
      id: '/createBet'
      path: '/createBet'
      fullPath: '/createBet'
      preLoaderRoute: typeof CreateBetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bets/$betUrl': {
      id: '/bets/$betUrl'
      path: '/bets/$betUrl'
      fullPath: '/bets/$betUrl'
      preLoaderRoute: typeof BetsBetUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BadgesRoute: BadgesRoute,
  CreateBetRoute: CreateBetRoute,
  LoginRoute: LoginRoute,
  OverviewRoute: OverviewRoute,
  BetsBetUrlRoute: BetsBetUrlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
